# Codemagic workflow para build y publicación iOS (Flutter)
# Basado en: https://docs.codemagic.io/yaml-quick-start/building-a-flutter-app
# y guía iOS: https://docs.codemagic.io/yaml-quick-start/building-a-native-ios-app/

workflows:
  ios-workflow:
    name: Wra5 iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: whalye
    environment:
      ios_signing:
        distribution_type: app_store  # app_store | ad_hoc | development
        bundle_identifier: com.whalyze.wra5
      vars:
        APP_STORE_APPLE_ID: 81323dfd-d9bc-47f8-835d-285965a3f97a
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install pods
        script: find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID") + 1))
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - dmarco.zaragoza@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups: []  # Añade nombres de grupos de testers si los tienes
        submit_to_app_store: false  # true cuando quieras enviar a revisión App Store
